spring:
  config:
    import:
      - postgresql-prod.yml
      - gemini.yml
server:
  forward-headers-strategy: framework
  url: https://fairy-band.com/api

# Notification Configuration
notification:
  discord:
    user-registration:
      enabled: ${DISCORD_USER_REGISTRATION_ENABLED:false}
      webhook-url: ${DISCORD_USER_REGISTRATION_WEBHOOK_URL:}
