spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: false
  config:
    import:
      - rss-feeds.yml

rss:
  scheduler:
    fetch:
      delay: ${RSS_FETCH_DELAY:1800000}
    process:
      delay: ${RSS_PROCESS_DELAY:900000}
    stats:
      cron: ${RSS_STATS_CRON:0 0 */3 * * *}
  ai:
    daily-limit: ${RSS_AI_DAILY_LIMIT:100}
