spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://newsletter:newsletter123@localhost:27017/newsletter?authSource=newsletter}
      auto-index-creation: true
  config:
    import:
      - rss-feeds.yml

rss:
  scheduler:
    fetch:
      delay: ${RSS_FETCH_DELAY:3600000}
    process:
      delay: ${RSS_PROCESS_DELAY:1800000}
    stats:
      cron: ${RSS_STATS_CRON:0 0 */6 * * *}
