events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    upstream api_backend {
        server newsletter-api:8080;
    }

    # HTTPS 서버
    server {
        # API 서버로 프록시
        location /api/ {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Prefix /api;

            # CORS 설정
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';

            sub_filter_once off;
            sub_filter 'href="/' 'href="/api/';
            sub_filter 'src="/' 'src="/api/';
        }

        # 글로벌 헬스체크 엔드포인트
        location /health {
            access_log off;
            add_header Content-Type application/json;
            return 200 '{"status":"UP"}';
        }

        # 헬스체크 엔드포인트
        location /api/health {
            proxy_pass http://api_backend/health;
            access_log off;
        }
    }
}
